### ISSUE TITLE
Okanagan Xslx files not working

### ISSUE THREAD

**Issue by Eveline36** [Its-pedram/workday2ics#1]
Does not work with Okanagan course xlsx or that is my guess. returns invalid xslx file. I am assuming its the okanagan xslx being different but could be something else or website is broken. Tried Edge and Chrome.

![image](https://github.com/Its-pedram/workday2ics/assets/92182724/635030cf-c737-415d-8dfa-52246fcd3f1d)

Tried multiple downloads of the file just to be safe.

![image](https://github.com/Its-pedram/workday2ics/assets/92182724/46eca35a-1a42-446c-b302-d32a24c86d97)

Screen shot of xlsx file with personal info removed:

![image](https://github.com/Its-pedram/workday2ics/assets/92182724/b5210c1a-2f3c-47e1-b67d-57ab7d62edc3)
 
Thanks in advance.

**Comment by Its-pedram** [comment]
Hello!

That's most likely because you're trying to export "My Enrolled Courses" instead of a saved schedule. The tool was built around parsing saved schedules when we started developing it.
As a temporary workaround, you can export a saved schedule, equivalent to your enrolled courses and use that (check the "Help! I'm lost!" button).
My registration time is in early July but I'm going to try to gather some samples from 4th year friends to redesign the parser.

Sorry for the inconvenience.

**Comment by zenialau** [comment]
Hi! We have updated the tool and it should now work with registered courses. Let us know if the issue persists. Thank you!
